name = "codefromanywhere_chatcompletions_main"
main = "main.ts"
compatibility_date = "2024-10-11"
assets = { directory= "./public" }

routes = [
  { pattern = "chatcompletions.com", custom_domain = true }
]

[[r2_buckets]]
bucket_name = "chatcompletions"
binding = "chatcompletions"
